# Generated by Django 3.0.7 on 2020-06-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TypePokemon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("hp", models.SmallIntegerField()),
                ("attack", models.SmallIntegerField()),
                ("defense", models.SmallIntegerField()),
                ("spell_attack", models.SmallIntegerField()),
                ("spell_defense", models.SmallIntegerField()),
                ("speed", models.SmallIntegerField()),
                ("generation", models.SmallIntegerField(default=1)),
                (
                    "type_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firsts",
                        to="pokemon.TypePokemon",
                    ),
                ),
                (
                    "type_2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondaries",
                        to="pokemon.TypePokemon",
                    ),
                ),
            ],
        ),
    ]
